import 'package:cinema/models/Seats.dart';
import 'package:cinema/models/categories.dart';
import 'package:cinema/models/showDay.dart';
import 'package:cinema/models/showTime.dart';
import 'package:flutter/widgets.dart';

class Film {
  double? price;
  String? name;
  AssetImage image;
  MovieCategory? category;
  String? discription;
  String? rating;
  String? duration;
  List<ShowDay>? showDays = [];
  Film(
      {this.name,
      required this.image,
      this.discription,
      this.category,
      this.rating,
      this.duration,
      required this.showDays,
      this.price});
}

List<Film> films = [
  Film(
    price: 12,
    name: "Encanto",
    category: MovieCategory.findCategory("comedy"),
    discription:
        "The Madrigals are an extraordinary family who live hidden in the mountains of Colombia in a charmed place called the Encanto. The magic of the Encanto has blessed every child in the family with a unique gift -- every child except Mirabel. However, she soon may be the Madrigals last hope when she discovers that the magic surrounding the Encanto is now in danger.",
    image: const AssetImage("assets/film1.jpg"),
    rating: "10/10",
    duration: "2h 10m",
    showDays: [
      ShowDay(month: "May", day: "3", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "C"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "C"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "C"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "D"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "30", showTimes: [
        ShowTime(time: "11:30", reservedSeats: [
          Seats(seatNumber: 13, isReserved: true),
          Seats(seatNumber: 44, isReserved: true),
          Seats(seatNumber: 19, isReserved: true),
          Seats(seatNumber: 11, isReserved: true),
          Seats(seatNumber: 20, isReserved: true),
          Seats(seatNumber: 30, isReserved: true),
        ]),
      ]),
    ],
  ),
  Film(
    price: 7,
    name: "Luca",
    category: MovieCategory.findCategory("comedy"),
    discription:
        "Set in a beautiful seaside town on the Italian Riviera, the original animated feature is a coming-of-age story about one young boy experiencing an unforgettable summer filled with gelato, pasta and endless scooter rides. Luca shares these adventures with his newfound best friend, but all the fun is threatened by a deeply held secret: he is a sea monster from another world just below the water's surface.",
    image: const AssetImage("assets/film2.jpg"),
    rating: "9.2/10",
    duration: "1h 40m",
    showDays: [
      ShowDay(month: "Apr", day: "24", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "25", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "26", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "27", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 4, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "28", showTimes: [
        ShowTime(time: "11:30", reservedSeats: [
          Seats(seatNumber: 13, isReserved: true),
          Seats(seatNumber: 44, isReserved: true),
          Seats(seatNumber: 19, isReserved: true),
          Seats(seatNumber: 11, isReserved: true),
          Seats(seatNumber: 20, isReserved: true),
          Seats(seatNumber: 30, isReserved: true),
        ]),
      ]),
    ],
  ),
  Film(
    price: 15.6,
    name: "Enola Holmes",
    category: MovieCategory.findCategory("Drama"),
    discription:
        "While searching for her missing mother, intrepid teen Enola Holmes uses her sleuthing skills to outsmart big brother Sherlock and help a runaway lord.",
    image: const AssetImage("assets/film3.jpg"),
    rating: "7.3/10",
    duration: "2h 0m",
    showDays: [
      ShowDay(month: "Apr", day: "24", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "25", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "26", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "27", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 4, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "28", showTimes: [
        ShowTime(time: "11:30", reservedSeats: [
          Seats(seatNumber: 13, isReserved: true),
          Seats(seatNumber: 44, isReserved: true),
          Seats(seatNumber: 19, isReserved: true),
          Seats(seatNumber: 11, isReserved: true),
          Seats(seatNumber: 20, isReserved: true),
          Seats(seatNumber: 30, isReserved: true),
        ]),
      ]),
    ],
  ),
  Film(
    price: 20,
    name: "Spider-Man: No Way Home",
    category: MovieCategory.findCategory("comedy"),
    discription:
        "With Spider-Man's identity now revealed, our friendly neighborhood web-slinger is unmasked and no longer able to separate his normal life as Peter Parker from the high stakes of being a superhero. When Peter asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    image: const AssetImage("assets/film4.jpg"),
    rating: "9.8/10",
    duration: "1h 52m",
    showDays: [
      ShowDay(month: "Apr", day: "24", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "25", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "26", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "27", showTimes: [
        ShowTime(time: "15:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 4, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"), //
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 7, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 8, isReserved: true, seatSide: "B"),
          Seats(seatNumber: 4, isReserved: true, seatSide: "B"),
        ]),
        ShowTime(time: "01:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "11:15", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:30", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "02:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
        ShowTime(time: "01:00", reservedSeats: [
          Seats(seatNumber: 3, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 20, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 10, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 11, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 2, isReserved: true, seatSide: "A"),
          Seats(seatNumber: 1, isReserved: true, seatSide: "A"),
        ]),
      ]),
      ShowDay(month: "Apr", day: "28", showTimes: [
        ShowTime(time: "11:30", reservedSeats: [
          Seats(seatNumber: 13, isReserved: true),
          Seats(seatNumber: 44, isReserved: true),
          Seats(seatNumber: 19, isReserved: true),
          Seats(seatNumber: 11, isReserved: true),
          Seats(seatNumber: 20, isReserved: true),
          Seats(seatNumber: 30, isReserved: true),
        ]),
      ]),
    ],
  ),
];
